# -*- coding: utf-8 -*-
"""Copy of gcn-form-understanding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rBtuZ32pWcS9-U6QcLTgPzjj8yW6eu72

# Form Understanding

## Dependencies
"""

"""## Import libraries"""

import torch.utils.data as data
import glob

from random import randrange
from dgl.nn.pytorch import GATConv, GraphConv
import matplotlib.pyplot as plt
import dgl.function as fn

from torch import nn
import torch

import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import os

import numpy as np
import xml.etree.ElementTree as ET
import networkx as nx
import pdb
import pagexml
import re
import torch 
import dgl
from torch.optim.lr_scheduler import StepLR

"""## Get ground truth"""

os.system('wget --no-check-certificate '+ "'https://docs.google.com/uc?export=download&id=1Y8UQe4-2uLti_YbnyZbwSWpUnC6kUZVj'"+' -O funsd.tar.gz')
os.system('tar -zxvf funsd.tar.gz')

"""## Auxiliary functions"""

def get_coords_and_transcript(pxml,textobject,key):
    regex = re.compile('[^a-zA-Z]')
    coords = pxml.getPoints(textobject)
    if len(coords)==4: 
        arg_max_coord=2
    else:
        arg_max_coord=1
    x0=int(coords[0].x)
    y0=int(coords[0].y)
    
    x1=int(coords[arg_max_coord].x)
    y1=int(coords[arg_max_coord].y)

    transcription = pxml.getTextEquiv(textobject)
    tag = pxml.getPropertyValue(textobject,key=key)
    line_transcript=[]
    w=transcription
               
    line_transcript.append(w)
    line_transcript = " ".join(line_transcript)
    line_transcript = line_transcript.strip()
    return x0,y0,x1,y1,line_transcript,tag



def adjacency_to_pairs_and_labels(am):
    pairs=[]
    labels=[]
    for i in range(am.shape[0]):
        for j in range(am.shape[1]):
            pairs.append((i,j))
            labels.append(am[i,j])

    return pairs,labels


def pxml2graph(file):
    # parse a pagexml file and return a dgl input graph and an edge target dictionary
    pagexml.set_omnius_schema()
    pxml = pagexml.PageXML()
    pxml.loadXml(file)
    pages = pxml.select('_:Page')
    node_id=[]
    node_label={}
    # Parse nodes (text boxes)
    for page in pages:
        pagenum = pxml.getPageNumber(page)
        regions = pxml.select('_:TextRegion',page)
        word_idx=0
        for region in regions:
            words=pxml.select('_:Word',region)
            for Word in words :
                node_id.append(word_idx)
                x0,y0,x1,y1,transcription,tag=get_coords_and_transcript(pxml,Word,'label')
                node_label[word_idx] = np.array([x0, y0])
                word_idx+=1

    # node adjacency matrix
                        
    am=np.ones((len(node_label),len(node_label)))

    target_am=np.zeros((len(node_id),len(node_id)))
    
    # nodes corresponding words in same groups are connected:
    for page in pages:
        pagenum = pxml.getPageNumber(page)
        regions = pxml.select('_:TextRegion',page)
        word_idx=0
        for region in regions:
            words=pxml.select('_:Word',region)
            first_region_word = word_idx
            for Word in words :
                node_id.append(word_idx)
                x0,y0,x1,y1,transcription,tag=get_coords_and_transcript(pxml,Word,'label')
                node_label[word_idx] = np.array([x0, y0])
                word_idx+=1
            last_region_word = word_idx

            target_am[first_region_word:last_region_word,first_region_word:last_region_word]=1

    G = nx.from_numpy_matrix(am)
    nx.set_node_attributes(G, node_label, 'position')
    node_label = torch.stack([torch.tensor(v['position']) for k,v in G.nodes.items()])
    pairs,labels= adjacency_to_pairs_and_labels(target_am)
    label_dict={}
    for k in range(len(pairs)):
        label_dict[pairs[k]]=labels[k]
    
    return G,label_dict

"""## Graph dataloader"""

"""#### Define Dataset Class
Pytorch provides an abstract class representig a dataset, ```torch.utils.data.Dataset```. We need to override two methods:

*   ```__len__``` so that ```len(dataset)``` returns the size of the dataset.
*   ```__getitem__``` to support the indexing such that ```dataset[i]``` can be used to get i-th sample
"""


class Pages(data.Dataset):
  """PagesDataset
  """
  
  def __init__(self, root_path, file_list):
    self.root = root_path
    self.file_list = file_list
    
    # List of files and corresponding labels
    self.files =glob.glob(root_path+'/*.xml')
                #os.listdir(root_path)
                
    
    
  def __getitem__(self, index):
    # Read the graph and label
    G,target =pxml2graph(os.path.join(self.root,self.files[index]))

    # Convert to DGL format
    '''g = dgl.DGLGraph()
    g.set_n_initializer(dgl.init.zero_initializer)
    g.set_e_initializer(dgl.init.zero_initializer)
    g.from_networkx(G, node_attrs=['position'])'''
    node_label = torch.stack([torch.tensor(v['position']) for k,v in G.nodes.items()]).float()
    node_label = (node_label - node_label.mean(0))/ node_label.std(0)

    g_in = dgl.transform.knn_graph(node_label,10)
    g_in = dgl.to_bidirected(g_in)
    #g_in = dgl.transform.knn_graph(G.ndata['position'], 40)
    
    g_in.ndata['position'] =node_label.float()

    #target_g = dgl.transform.knn_graph(node_label,10)
    return g_in, target
  
  def label2class(self, label):
    # Converts the numeric label to the corresponding string
    return self.unique_labels[label]
  
  def __len__(self):
    # Subset length
    return len(self.files)

# Define the corresponding subsets for train, validation and test.
#trainset = Pages(os.path.join(dataset_path, distortion), 'train.cxl')
"""### Prepare DataLoader

```torch.utils.data.DataLoader``` is an iterator which provides:


*   Data batching
*   Shuffling the data
*   Parallel data loading

In our specific case, we need to deal with graphs of many sizes. Hence, we define a new collate function makin guse of the method ```dgl.batch```.
"""

from torch.utils.data import DataLoader

def collate(samples):
    # The input `samples` is a list of pairs
    #  (graph, label).
    graphs, labels = map(list, zip(*samples))
    batched_graph = dgl.batch(graphs)
    #labels = dgl.batch(labels)
    return batched_graph, labels#torch.tensor(labels)

"""## Model"""

class Net(nn.Module):
    def __init__(self, in_dim, hidden_dim):
        super(Net, self).__init__()
        #self.conv1 = GraphConv(in_dim, hidden_dim)
        #self.conv2 = GraphConv(hidden_dim, hidden_dim)
        #self.conv3 = GraphConv(hidden_dim, hidden_dim)

        self.conv1 = GATConv(in_dim, hidden_dim, 4, residual=True, activation=F.relu)
        self.conv2 = GATConv(4*hidden_dim, hidden_dim, 4, residual=True, activation=F.relu)
        self.conv3 = GATConv(4*hidden_dim, hidden_dim, 4, residual=True)

        self.mlp = nn.Sequential(nn.Linear(hidden_dim, hidden_dim), nn.ReLU(True), nn.Linear(hidden_dim, 1), nn.Sigmoid())
        self.score = nn.CosineSimilarity()

    def get_complete_graph_and_pairs(self,num_nodes):
        G = nx.complete_graph(num_nodes)
        
        g = dgl.DGLGraph()
        g.from_networkx(G)
        pairs = torch.t(torch.stack([g.edges()[0],g.edges()[1]]))
        return g,pairs

    def calc_score(self,g):
        #pairs = torch.t(torch.stack([g.edges()[0],g.edges()[1]]))

        # get hidden state of all source destination pairs and calculate their edge score
        s = g.ndata['h'][g.edges()[0]]
        d = g.ndata['h'][g.edges()[1]]
        #s = g.ndata['h'][pairs[:,0]]
        #d = g.ndata['h'][pairs[:,1]]
        score = self.mlp((s-d).abs()).squeeze()
        #score = F.sigmoid(torch.bmm(s.unsqueeze(1),d.unsqueeze(2)).squeeze())
        #score = self.score(s,d)

        return score

    def forward(self, g):
        # For undirected graphs, in_degree is the same as
        # out_degree.
        h = g.ndata['position']

        if torch.cuda.is_available():
          h = h.cuda() 
        #h = F.relu(self.conv1(g, h))
        #h = F.relu(self.conv2(g, h))
        #h = self.conv3(g, h)
        h = self.conv1(g,h)
        h = h.view(h.shape[0], -1)

        h = self.conv2(g,h)
        h = h.view(h.shape[0], -1)

        h = self.conv3(g,h)
        h = h.mean(1)
        
        g.ndata['h'] = h
        score = self.calc_score(g)
        #hg = dgl.mean_nodes(g, 'h')
        #return self.classify(hg)
        return score

"""## Define data loaders"""

trainset = Pages('.','')
validset = Pages('.','')
testset = Pages('.','')

train_loader = DataLoader(trainset, batch_size=1, shuffle=True,collate_fn=collate)
valid_loader = DataLoader(validset, batch_size=1, collate_fn=collate)
test_loader = DataLoader(testset, batch_size=1, collate_fn=collate)

"""# Train step"""

def accuracy(output, target):
  """Accuacy given a logit vector output and a target class
  """
  _, pred = output.topk(1)
  pred = pred.squeeze()
  correct = pred == target
  correct = correct.float()
  return correct.sum() * 100.0 / correct.shape[0]

"""## Training setup"""

def train(model):
    if torch.cuda.is_available():
        model = model.cuda()
    loss_func = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    scheduler = StepLR(optimizer, 20, gamma = 0.9)
    model.train()
    
    def random_choice(tensor,k=100):
        perm = torch.randperm(tensor.size(0))
        idx = perm[:k]
        samples = tensor[idx]
        return samples

    epoch_losses = []
    train_log = open('train_log.txt','w')
    epoch_loss = 0

    for epoch in range(100):
        for iter, (bg, blab) in enumerate(train_loader):
          
            optimizer.zero_grad()
            prediction = model(bg)
            target_edges = blab[0]

            input_edges = torch.stack(bg.edges()).t().tolist()
            
            edges = list(map(tuple, input_edges))
            target = torch.tensor([target_edges[e] for e in edges])

            class_weights = target.shape[0]*torch.ones(target.shape)

            class_weights[target.bool()] /= 2*target.sum()
            class_weights[(1-target).bool()] /= 2*(1-target).sum()
            
            loss = F.binary_cross_entropy(prediction,target,weight=class_weights)

            print('\t* Epoch '+str(epoch)+' '+ str(float(iter/len(train_loader))) +' loss '+str(float(loss)) + ' lr' + str(scheduler.get_lr()[0]))
        
            loss.backward()
            optimizer.step()
            scheduler.step()

            prediction[prediction>0.5] = 1
            prediction[prediction<=0.5] = 0

            print("ACCURACY:",float((prediction == target).sum())/prediction.shape[0])
            print("PRECISION:", ((prediction == target)[target.bool()].float().sum()/prediction.sum()).item())
            print("RECALL:", ((prediction == target)[target.bool()].float().sum()/target.sum()).item())
    return model

"""# Main"""

#def main():
model_path = 'model.pt'
if os.path.exists(model_path):
    model = torch.load(model_path)
else:
    
    model = Net(2, 128)

    model = train(model)
    torch.save(model,'model.pt')


#if __name__ == "__main__":
#    main()

def visualize_graph(g):
    position = np.array(g.ndata['position'])
    g = g.to_networkx()
    nx.draw(g, pos=position, arrows=False)
    plt.show()

def edges_list_to_dgl(edges):
    g = dgl.DGLGraph()
    g.add_edges(edges[:,0],edges[:,1])
    return g

bg,blab = trainset.__getitem__(0)
pdb.set_trace()
# X
G = bg.to_networkx(node_attrs=['position'])
position = {k: v.numpy().astype('float') for k, v in dict(G.nodes(data='position')).items()}
nx.draw(G, pos=position, arrows=False)
plt.savefig('X.png')
plt.clf()
target_edges = blab

# Y
input_edges = torch.stack(bg.edges()).t().tolist()
            
edges = list(map(tuple, input_edges))
target = torch.tensor([target_edges[e] for e in edges])

G_label = dgl.DGLGraph()
G_label.add_nodes(G.number_of_nodes())
target_edges = torch.t(torch.stack([bg.edges()[0][target.bool()],bg.edges()[1][target.bool()]]))
G_label.add_edges(target_edges[:,0],target_edges[:,1])

G_label= G_label.to_networkx()
nx.draw(G_label, pos=position, arrows=False)
plt.savefig('Y.png')
plt.clf()
# Y'
prediction = model(bg)
prediction[prediction<0.5]=0.
prediction[prediction>0.1]=1.
G_out = dgl.DGLGraph()
G_out.add_nodes(G.number_of_nodes())
pred_edges = torch.t(torch.stack([bg.edges()[0][prediction.bool()],bg.edges()[1][prediction.bool()]]))
G_out.add_edges(pred_edges[:,0],pred_edges[:,1])
G_out = G_out.to_networkx()
nx.set_node_attributes(G_out, position, 'position')


nx.draw(G_out, pos=position, arrows=False)
plt.savefig('Ypred.png')
plt.clf()
bg
